#!/usr/bin/env bash

. venv/bin/activate

function launch {
	python app.py 5555 &
	echo $! > .server.pid
}

function terminate {
	kill `cat .server.pid`
	rm .server.pid
}

launch
gabbi-run localhost:5555 < test_json.yaml
terminate

launch
gabbi-run -r gabbi_html localhost:5555 < test_html.yaml
terminate
